export const ETSY_LISTING_FEE = 0.20;
export const ETSY_TRANSACTION_PERCENTAGE = 6.5;
export const PAYMENT_PROCESSING_PERCENTAGE = 3;
export const PAYMENT_PROCESSING_FIXED_FEE = 0.25;
export const ETSY_OFFSITE_AD_PERCENTAGE_MORE_THAN_10K_SALES = 12;
export const ETSY_OFFSITE_AD_PERCENTAGE_LESS_THAN_10K_SALES = 15;